name: datalad_binder

channels:
  - default
  - conda-forge

dependencies:
  - python=3.8.*
  - pip
  - datalad=0.15.*
  - pip:
      - nbgitpuller
      - bash_kernel
      - jupyter-notebookparams
      - git+https://github.com/choldgraf/jupyter-http-server@master
